global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Main booking application metrics
  - job_name: 'clinic-booking-app'
    static_configs:
      - targets: ['booking-app:3000']
    metrics_path: '/api/dashboard/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']
    scrape_interval: 15s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Optional: Add more targets as needed
  # - job_name: 'additional-service'
  #   static_configs:
  #     - targets: ['service:port']